# Generated by Django 6.0 on 2025-12-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_id', models.CharField(max_length=25, unique=True)),
                ('mem_pw', models.CharField(max_length=200)),
                ('mem_nm', models.CharField(max_length=50)),
                ('nick_nm', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('cr_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
