# Generated by Django 6.0 on 2025-12-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
