# Generated by Django 6.0 on 2025-12-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_myuser_base_addr_myuser_cr_dt_myuser_detail_addr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cr_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
