# Generated by Django 6.0 on 2025-12-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='mthumbnail',
            field=models.TextField(null=True),
        ),
    ]
