# Generated by Django 6.0 on 2025-12-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_magazine_mthumbnail'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='mlike',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_myuser', to='member.myuser'),
        ),
    ]
