# Generated by Django 6.0 on 2025-12-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_alter_magazine_mfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine_code',
            name='id',
        ),
        migrations.AlterField(
            model_name='magazine_code',
            name='mtype',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
