# Generated by Django 6.0 on 2025-12-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_remove_magazine_code_id_alter_magazine_code_mtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine_code',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='magazine_code',
            name='mtype',
            field=models.CharField(max_length=2),
        ),
    ]
