# Generated by Django 6.0 on 2025-12-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
