# Generated by Django 6.0 on 2025-12-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurants_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='locno',
            field=models.IntegerField(default=0),
        ),
    ]
